<?php function money($minor){ return '₦'.number_format($minor/100, 2); } ?>
<!doctype html><html lang="en" class="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Intern Dashboard · ThriveWell OS</title><link rel="stylesheet" href="/build/app.css"><script defer src="/build/app.js"></script></head>
<body><div class="ambient"></div><div class="app-shell">
<aside class="sidebar"><div class="logo"><span class="leaf">✦</span><div><strong>ThriveWell</strong><small>Intern Portal</small></div></div><nav><?php foreach ([['Dashboard','⌂','active'],['My Schedule','◴',''],['My Clients','♧',''],['Sessions','◎',''],['Session Notes','▧',''],['Listening Bonus','◉','new'],['Wallet & Payouts','▤',''],['Resources','◇',''],['Supervision','♙',''],['CPD & Training','☑',''],['Community','♧','12'],['Messages','✉','3'],['Settings','⚙','']] as $item): ?><a class="<?= $item[2]==='active'?'active':'' ?>" href="#"><span><?= $item[1] ?></span><?= $item[0] ?><?php if($item[2] && $item[2] !== 'active'): ?><b><?= $item[2] ?></b><?php endif; ?></a><?php endforeach; ?></nav><section class="upgrade"><strong>⭐ Upgrade to Tier 2</strong><p>Unlock higher earnings (35% revenue share)</p><button>View Requirements</button></section><section class="support">🎧 <strong>Need Support?</strong><p>We're here for you<br>support@thrivewell.org</p></section></aside>
<main class="content"><header class="topbar"><div><h1>Good morning, <?= htmlspecialchars(explode(' ', $user['name'])[0]) ?>! 👋</h1><p>You're making a real difference in someone's life today.</p></div><div class="top-actions"><button class="status-dot">● Available for Sessions</button><button class="bell">♢<sup><?= count($data['notifications']) ?></sup></button><button class="profile"><img src="<?= $user['avatar'] ?>" alt="<?= htmlspecialchars($user['name']) ?>"><span><?= htmlspecialchars($user['name']) ?><small><?= htmlspecialchars($user['role_label']) ?> (Tier 1)</small></span>⌄</button><button id="themeToggle" aria-label="Toggle theme">☾</button><a class="logout" href="/logout">Logout</a></div></header>
<section class="kpi-grid"><?php foreach($data['kpis'] as $kpi): ?><article class="card stat <?= $kpi['tone'] ?>"><div class="stat-icon">●</div><span><?= $kpi['label'] ?></span><strong><?= $kpi['value'] ?></strong><small><?= $kpi['trend'] ?></small><svg viewBox="0 0 180 24"><path d="M0 15 C15 5 20 25 35 14 S55 10 70 18 90 4 105 12 125 25 140 13 160 8 180 15"/></svg></article><?php endforeach; ?></section>
<section class="dashboard-grid"><article class="card wide"><div class="card-head"><h2>Today's Schedule</h2><button>View Full Schedule</button></div><?php foreach($data['today'] as $s): ?><div class="schedule-row"><time><?= date('g:i A', strtotime($s['starts_at'])) ?><small><?= $s['duration_minutes'] ?> min</small></time><img src="<?= $s['client_avatar'] ?>" alt=""><div><strong><?= htmlspecialchars($s['client_name']) ?></strong><span><?= htmlspecialchars($s['topic']) ?></span></div><em class="pill <?= $s['status'] ?>"><?= ucfirst($s['status']) ?></em><span>▣ ›</span></div><?php endforeach; ?><a class="link">View Full Schedule →</a></article>
<article class="card"><div class="card-head"><h2>Recent Sessions</h2><button>View All⌄</button></div><?php foreach(array_slice($data['recent'],0,4) as $s): ?><div class="recent-row"><img src="<?= $s['client_avatar'] ?>" alt=""><div><strong><?= htmlspecialchars($s['client_name']) ?></strong><span><?= htmlspecialchars($s['topic']) ?></span></div><time><?= date('M j, Y', strtotime($s['starts_at'])) ?><small><?= date('g:i A', strtotime($s['starts_at'])) ?></small></time><b>★ <?= $s['rating'] ?></b></div><?php endforeach; ?><a class="link">View All Sessions →</a></article>
<article class="card wallet"><div class="card-head"><h2>Listening Bonus</h2><button>This Month⌄</button></div><strong><?= money($data['wallet']['available']) ?></strong><span>Available Balance ◉</span><button>Withdraw Funds</button><dl><dt>Total Earned</dt><dd><?= money(15600000) ?></dd><dt>Pending Payout</dt><dd><?= money($data['wallet']['pending']) ?></dd><dt>Total Withdrawn</dt><dd><?= money($data['wallet']['withdrawn']) ?></dd></dl><a class="link">View Earnings Breakdown →</a></article>
<article class="card chart"><div class="card-head"><h2>Earnings Overview</h2><button>This Year⌄</button></div><div class="area-chart"><?php foreach($data['earnings'] as $e): ?><span style="--h:<?= max(20, $e['amount_minor']/160000) ?>px" data-label="<?= $e['period'] ?>"></span><?php endforeach; ?></div></article>
<article class="card chart"><div class="card-head"><h2>Performance Overview</h2><small>━ You &nbsp; -- Average</small></div><div class="radar"><div>Empathy<br><b>4.9</b></div><svg viewBox="0 0 200 200"><polygon points="100,20 174,75 146,164 54,164 26,75"/><polygon class="fill" points="100,38 160,82 135,150 65,150 40,82"/></svg><div class="radar-labels">Professionalism 4.8 · Communication 4.8 · Reliability 4.9 · Knowledge 4.7</div></div></article>
<article class="card cpd"><div class="card-head"><h2>CPD Progress</h2><button>View CPD Hub</button></div><div class="ring" style="--pct:65"><b>65%</b><span>Overall Progress</span></div><dl><dt>Completed</dt><dd>13 Modules</dd><dt>In Progress</dt><dd>5 Modules</dd><dt>Remaining</dt><dd>7 Modules</dd></dl><a class="link">Continue Learning →</a></article></section>
<section class="care-strip"><div>💚 <strong>You're changing lives!</strong><span>Remember to take care of your wellbeing too.</span></div><button>☕ Take a Break</button><button>♡ Wellness Check</button><button>♧ Talk to Supervisor</button></section>
<section class="safety card"><strong>Kale AI safety boundary:</strong> Kale supports reflection only. It does not replace therapy, diagnose, or advise on medication. Crisis concerns route to human support first.</section>
</main></div></body></html>
