<?php
return [
    "CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, label TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS permissions (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, description TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS role_permission (role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL, PRIMARY KEY(role_id, permission_id))",
    "CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL, role_id INTEGER NOT NULL, avatar TEXT, status TEXT DEFAULT 'available', email_verified_at TEXT, consent_version TEXT DEFAULT '2026.05', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS users_role_status_index ON users(role_id, status)",
    "CREATE TABLE IF NOT EXISTS dashboard_preferences (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, theme TEXT DEFAULT 'system', reduced_motion INTEGER DEFAULT 0, high_contrast INTEGER DEFAULT 0, density TEXT DEFAULT 'comfortable', widgets_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS counselling_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, intern_id INTEGER NOT NULL, client_name TEXT NOT NULL, client_avatar TEXT, topic TEXT NOT NULL, starts_at TEXT NOT NULL, duration_minutes INTEGER NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, rating REAL, bonus_minor INTEGER DEFAULT 0, created_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS sessions_intern_starts_status_index ON counselling_sessions(intern_id, starts_at, status)",
    "CREATE TABLE IF NOT EXISTS earnings (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, period TEXT NOT NULL, amount_minor INTEGER NOT NULL, source TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS earnings_user_period_index ON earnings(user_id, period)",
    "CREATE TABLE IF NOT EXISTS cpd_modules (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, progress INTEGER NOT NULL, due_at TEXT, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, type TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS notifications_user_read_index ON notifications(user_id, read_at)",
    "CREATE TABLE IF NOT EXISTS wellness_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, action_type TEXT NOT NULL, completed_at TEXT, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS ai_companion_cards (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, safety_label TEXT NOT NULL, requires_human_review INTEGER DEFAULT 0, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS crisis_incidents (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, concern TEXT NOT NULL, tier TEXT NOT NULL, status TEXT NOT NULL, human_review_required INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS crisis_user_status_index ON crisis_incidents(user_id, status)",
    "CREATE TABLE IF NOT EXISTS intern_clients (id INTEGER PRIMARY KEY AUTOINCREMENT, intern_id INTEGER NOT NULL, name TEXT NOT NULL, avatar TEXT, focus_area TEXT NOT NULL, next_step TEXT NOT NULL, wellbeing_signal TEXT NOT NULL, consent_to_share INTEGER DEFAULT 0, last_seen_at TEXT, created_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS intern_clients_intern_signal_index ON intern_clients(intern_id, wellbeing_signal)",
    "CREATE TABLE IF NOT EXISTS supervision_tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, supervisor TEXT NOT NULL, priority TEXT NOT NULL, due_at TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS supervision_user_due_index ON supervision_tasks(user_id, due_at)",
    "CREATE TABLE IF NOT EXISTS resource_library_items (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL, reading_minutes INTEGER NOT NULL, accessibility_tags TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS dashboard_widgets (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, widget_type TEXT NOT NULL, position INTEGER NOT NULL, enabled INTEGER DEFAULT 1, config_json TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS workflow_nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, node_type TEXT NOT NULL, status TEXT NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, config_json TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS form_builder_fields (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL, field_type TEXT NOT NULL, required INTEGER DEFAULT 0, help_text TEXT NOT NULL, sort_order INTEGER NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT NOT NULL, auditable_type TEXT NOT NULL, auditable_id INTEGER, metadata TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS audit_action_created_index ON audit_logs(action, created_at)"
];
