<?php
return [
    "CREATE TABLE IF NOT EXISTS roles (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, label TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS permissions (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, description TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS role_permission (role_id INTEGER NOT NULL, permission_id INTEGER NOT NULL, PRIMARY KEY(role_id, permission_id))",
    "CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL, role_id INTEGER NOT NULL, avatar TEXT, status TEXT DEFAULT 'available', email_verified_at TEXT, consent_version TEXT DEFAULT '2026.05', created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS users_role_status_index ON users(role_id, status)",
    "CREATE TABLE IF NOT EXISTS dashboard_preferences (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, theme TEXT DEFAULT 'system', reduced_motion INTEGER DEFAULT 0, high_contrast INTEGER DEFAULT 0, density TEXT DEFAULT 'comfortable', widgets_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS counselling_sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, intern_id INTEGER NOT NULL, client_name TEXT NOT NULL, client_avatar TEXT, topic TEXT NOT NULL, starts_at TEXT NOT NULL, duration_minutes INTEGER NOT NULL, type TEXT NOT NULL, status TEXT NOT NULL, rating REAL, bonus_minor INTEGER DEFAULT 0, created_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS sessions_intern_starts_status_index ON counselling_sessions(intern_id, starts_at, status)",
    "CREATE TABLE IF NOT EXISTS earnings (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, period TEXT NOT NULL, amount_minor INTEGER NOT NULL, source TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS earnings_user_period_index ON earnings(user_id, period)",
    "CREATE TABLE IF NOT EXISTS cpd_modules (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, status TEXT NOT NULL, progress INTEGER NOT NULL, due_at TEXT, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS notifications (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, type TEXT NOT NULL, read_at TEXT, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS notifications_user_read_index ON notifications(user_id, read_at)",
    "CREATE TABLE IF NOT EXISTS wellness_actions (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, description TEXT NOT NULL, action_type TEXT NOT NULL, completed_at TEXT, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS ai_companion_cards (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, body TEXT NOT NULL, safety_label TEXT NOT NULL, requires_human_review INTEGER DEFAULT 0, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS crisis_incidents (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, concern TEXT NOT NULL, tier TEXT NOT NULL, status TEXT NOT NULL, human_review_required INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS crisis_user_status_index ON crisis_incidents(user_id, status)",
    "CREATE TABLE IF NOT EXISTS intern_clients (id INTEGER PRIMARY KEY AUTOINCREMENT, intern_id INTEGER NOT NULL, name TEXT NOT NULL, avatar TEXT, focus_area TEXT NOT NULL, next_step TEXT NOT NULL, wellbeing_signal TEXT NOT NULL, consent_to_share INTEGER DEFAULT 0, last_seen_at TEXT, created_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS intern_clients_intern_signal_index ON intern_clients(intern_id, wellbeing_signal)",
    "CREATE TABLE IF NOT EXISTS supervision_tasks (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, supervisor TEXT NOT NULL, priority TEXT NOT NULL, due_at TEXT NOT NULL, status TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS supervision_user_due_index ON supervision_tasks(user_id, due_at)",
    "CREATE TABLE IF NOT EXISTS resource_library_items (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, category TEXT NOT NULL, description TEXT NOT NULL, reading_minutes INTEGER NOT NULL, accessibility_tags TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS dashboard_widgets (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, widget_type TEXT NOT NULL, position INTEGER NOT NULL, enabled INTEGER DEFAULT 1, config_json TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS workflow_nodes (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, title TEXT NOT NULL, node_type TEXT NOT NULL, status TEXT NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, config_json TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS form_builder_fields (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, label TEXT NOT NULL, field_type TEXT NOT NULL, required INTEGER DEFAULT 0, help_text TEXT NOT NULL, sort_order INTEGER NOT NULL, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS credential_documents (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, document_type TEXT NOT NULL, title TEXT NOT NULL, storage_disk TEXT NOT NULL DEFAULT 'private', storage_path TEXT NOT NULL, file_hash TEXT NOT NULL, status TEXT NOT NULL, reviewer_id INTEGER, revision_reason TEXT, submitted_at TEXT, reviewed_at TEXT, expires_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, deleted_at TEXT)",
    "CREATE INDEX IF NOT EXISTS credential_documents_user_status_index ON credential_documents(user_id, status)",
    "CREATE TABLE IF NOT EXISTS credential_reviews (id INTEGER PRIMARY KEY AUTOINCREMENT, credential_document_id INTEGER NOT NULL, reviewer_id INTEGER NOT NULL, decision TEXT NOT NULL, notes TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS credential_reviews_document_index ON credential_reviews(credential_document_id)",
    "CREATE TABLE IF NOT EXISTS verification_badges (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, badge TEXT NOT NULL, level TEXT NOT NULL, status TEXT NOT NULL, issued_at TEXT, expires_at TEXT, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS verification_badges_user_status_index ON verification_badges(user_id, status)",
    "CREATE TABLE IF NOT EXISTS signed_download_tokens (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, credential_document_id INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, purpose TEXT NOT NULL, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS onboarding_drafts (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL UNIQUE, role TEXT NOT NULL, current_step INTEGER NOT NULL DEFAULT 1, payload_json TEXT NOT NULL, updated_at TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS onboarding_drafts_role_step_index ON onboarding_drafts(role, current_step)",
    "CREATE TABLE IF NOT EXISTS onboarding_profiles (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, role TEXT NOT NULL, preferred_name TEXT NOT NULL, support_goal TEXT NOT NULL, accessibility_preferences TEXT NOT NULL, onboarding_status TEXT NOT NULL, completed_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS onboarding_profiles_user_role_index ON onboarding_profiles(user_id, role)",
    "CREATE TABLE IF NOT EXISTS consent_records (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, consent_version TEXT NOT NULL, consent_scope TEXT NOT NULL, granted INTEGER NOT NULL, ip_address TEXT, user_agent TEXT, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS consent_records_user_scope_index ON consent_records(user_id, consent_scope)",
    "CREATE TABLE IF NOT EXISTS email_verification_tokens (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER NOT NULL, token TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, used_at TEXT, created_at TEXT NOT NULL)",
    "CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, action TEXT NOT NULL, auditable_type TEXT NOT NULL, auditable_id INTEGER, metadata TEXT NOT NULL, created_at TEXT NOT NULL)",
    "CREATE INDEX IF NOT EXISTS audit_action_created_index ON audit_logs(action, created_at)"
];
